# Generated by Django 6.1 on 2026-08-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название ачивки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ачивка',
                'verbose_name_plural': 'Ачивки',
            },
        ),
        migrations.CreateModel(
            name='AchievementAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Основание выдачи')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boost.achievement', verbose_name='Ачивка')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_given', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выдача ачивки',
                'verbose_name_plural': 'Выдачи ачивок',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в рейтинге')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.activity', verbose_name='Активность')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Рейтинг команды',
                'verbose_name_plural': 'Рейтинги команд',
                'ordering': ['position'],
                'unique_together': {('team', 'activity')},
            },
        ),
    ]
