# Generated by Django 6.1 on 2026-08-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Начисление'), ('spend', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('points', models.IntegerField(verbose_name='Количество баллов')),
                ('description', models.TextField(blank=True, verbose_name='Описание операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Операция с баллами',
                'verbose_name_plural': 'Операции с баллами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamPointsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.IntegerField(default=0, verbose_name='Всего заработано')),
                ('total_spent', models.IntegerField(default=0, verbose_name='Всего потрачено')),
                ('current_balance', models.IntegerField(default=0, verbose_name='Текущий баланс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sigma.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Баланс команды',
                'verbose_name_plural': 'Балансы команд',
            },
        ),
    ]
